### ISSUE TITLE
NodeJS v8.9~ 対応

### ISSUE THREAD

**Issue by kaave** [framelunch/scaffold-frontend#17]
## 詳細

めでたくversion 8もLTSになってパフォーマンスやらなんやら改善されてるらしいのでバージョンあげたいんだけど、
`postcss-simple-vars` がエラー吹いてる雰囲気

```text
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Lexical error on line 1. Unrecognized text.
$end - $start
^
    at Parser.parseError (/Volumes/SubVolume/Projects/FL/scaffold-frontend/node_modules/postcss-fixes/node_modules/reduce-css-calc/dist/parser.js:160:21)
    at Object.parseError (/Volumes/SubVolume/Projects/FL/scaffold-frontend/node_modules/postcss-fixes/node_modules/reduce-css-calc/dist/parser.js:310:28)
    at Object.next (/Volumes/SubVolume/Projects/FL/scaffold-frontend/node_modules/postcss-fixes/node_modules/reduce-css-calc/dist/parser.js:565:25)
    at Object.lex (/Volumes/SubVolume/Projects/FL/scaffold-frontend/node_modules/postcss-fixes/node_modules/reduce-css-calc/dist/parser.js:575:22)
    at lex (/Volumes/SubVolume/Projects/FL/scaffold-frontend/node_modules/postcss-fixes/node_modules/reduce-css-calc/dist/parser.js:197:27)
    at Parser.parse (/Volumes/SubVolume/Projects/FL/scaffold-frontend/node_modules/postcss-fixes/node_modules/reduce-css-calc/dist/parser.js:210:26)
    at /Volumes/SubVolume/Projects/FL/scaffold-frontend/node_modules/postcss-fixes/node_modules/reduce-css-calc/dist/index.js:35:30
    at walk (/Volumes/SubVolume/Projects/FL/scaffold-frontend/node_modules/postcss-value-parser/lib/walk.js:15:13)
    at ValueParser.walk (/Volumes/SubVolume/Projects/FL/scaffold-frontend/node_modules/postcss-value-parser/lib/index.js:18:5)
    at exports.default (/Volumes/SubVolume/Projects/FL/scaffold-frontend/node_modules/postcss-fixes/node_modules/reduce-css-calc/dist/index.js:29:51)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kaave** [comment]
単にbuildコマンド時にPostCSSプラグインちゃんと読み込んでないだけだった！
